### ISSUE TITLE
Bug in v1.0.2: Alarm Panel Always Shows "Armed Home" Regardless of Arming Mode

### ISSUE THREAD

**Issue by piotr0777** [leshqo/satel_integra_ext-ha#10]
I noticed a minor bug introduced in version v1.0.2: regardless of the arming mode (0, 1, 2, or 3), the Alarm Panel in Home Assistant always displays "Armed Home."

Each zone in Satel Integra supports four arming modes:
0 - Full
1 - Full + bypass
2 - Stay
3 - Stay, delay=0

The integration, however, only recognizes two armed states:
- Armed Home
- Armed Away

It seems that modes 0 should map to Armed Away, while modes 1, 2 and 3 should map to Armed Home. This logic was likely implemented in earlier versions (prior to v1.0.2), but the current version appears to have changed this mapping (by always displaying Armed Home, regardless of the real alarm arm type)

The arming actions in Home Assistant work currently as follows:
- Clicking Armed Away arms the system as type 0 (Full) - but still after arming, the Alarm Panel would display "Armed Home" anyway
- Clicking Armed Home arms the system as type 1 (Full + bypass)

Update:
I also noticed that the Home Assistant Alarm Panel actually has a third arm mode (Armed Night). However, I’m not sure if Armed Night was properly configured in the Satel Integra integration before version v1.0.2. This might be worth revisiting to clarify the intended mapping and functionality.

**Comment by michaljonik** [comment]
Are you sure you're not using **1.0.2-beta1**?
Because this exact regression bug was fixed between **1.0.2-beta1** and final release **1.0.2**.

Armed Night was never used in this integration. Does Satel have anything similar?

**Comment by piotr0777** [comment]
You are right, I was using 1.0.2-beta1. Everything works fine now. Sorry to bother you.

In Satel there are only these modes available:
0 - Full
1 - Full + bypass
2 - Stay
3 - Stay, delay=0

Initially I was thinking that maybe type 2 (stay) could be configured as night mode, but actually after reading about this mode a bit more it doesn't seem to be very useful mode for a regular home owner and it doesn't really work as night mode.
2 - wejścia o typie reakcji 3. OPÓŹNIONA WEWNĘTRZNA nie będą czuwać, 8. ZEWNĘTRZNA wywołają cichy alarm, a pozostałe alarm głośny
2 - Inputs with reaction type 3. DELAYED INTERNAL will not be armed, 8. EXTERNAL will trigger a silent alarm, and the rest will trigger a loud alarm.

**Comment by michaljonik** [comment]
No worries :)

I don't use the Night Mode. At night I actually use the Home Mode.
In fact I use a Template Alarm which then controls two different Satel zones depending on the armed mode:
1. interior motion sensors (armed when away only)
2. doors and windows sensors (armed when away or home)

**Comment by piotr0777** [comment]
That's also what I do :) ...separate Template Alarm controlling 3 Satel zones. Thanks again for making this integration much better than the original one included in HASS.
