### ISSUE TITLE
Commands for multiple devices fail if one of them arms/disarms the system

### ISSUE THREAD

**Issue by MBarti** [leshqo/satel_integra_ext-ha#2]
The fix for switching multiple devices does not work, when in a scene you also want to arm or disarm the alarm (e.g. a night scene, turning off all lights and arming the Satel system) - the switches work, but the alarm doesn't start to arm.

For reference:
https://github.com/home-assistant/core/issues/42111#issuecomment-1721756271

**Comment by michaljonik** [comment]
That should work in the latest release. 
Now all commands are grouped by type and send together (arming multiple zones, enabling multiple outputs, etc) and the commands are queued properly and send one by one waiting for Satel confirmations.

**Comment by piotr0777** [comment]
@michaljonik Thank you for updating the Satel integration! Sending multiple commands at once works perfectly—it was exactly the feature I’d been needing. This update has resolved many of my issues.

**Comment by michaljonik** [comment]
I'm glad it works for you! 
I was just fixing my own issues ;)
