### ISSUE TITLE
Zone Keyboards Show "Unknown" Status Instead of Real Status

### ISSUE THREAD

**Issue by piotr0777** [leshqo/satel_integra_ext-ha#7]
### Issue: Zone Keyboards Show "Unknown" Status Instead of Real Status

**Description:**
The integration was functioning well for a few days, accurately displaying status updates (armed, disarmed, pending, etc.) for my Zone Keyboards (Strefy). However, after a couple of days, the Zone Keyboards in HASS began displaying an "Unknown" status instead of the correct real status.

I've been using original HASS satel integration for around a year before and I've not encountered any issues with zone status updates during that time.

**Possible Cause:**
I made some adjustments in the DloadX program to add additional outputs, which should not have affected the zones directly. However, this could still be related to the issue.
Additionally, I encountered a strange behavior with the new outputs:
1. New outputs configured on output numbers 11-15 did not appear in the Home Assistant GUI, even though they were properly set up in the YAML file.
2. Same new outputs configured on another output numbers (121-125) appeared in the HA GUI immediately.
This inconsistency might be relevant to the unknown status issue.

**Troubleshooting Steps Taken:**
Integration Reconfiguration - I deleted the entire satel integration configuration from the YAML file, removed manually all entities from the Home Assistant GUI, and re-added the satel configuration in YAML again. Unfortunately, this did not resolve the issue.

**Request for Assistance:**
Any insights or suggestions for resolving this would be greatly appreciated. If there are specific diagnostics or logs I should provide, please let me know.

**Firmware:**
I have not made any changes to the firmware for around 1 year. Currently using version:
Communication module: ETHM-1 V2.10
Alarm system: Integra 256 Plus 1.22 PL

<img width="590" alt="zone1" src="https://github.com/user-attachments/assets/5e9e8ff6-b5ef-4f46-8bdf-e868b7d38168">
<img width="590" alt="zone2" src="https://github.com/user-attachments/assets/b7d906e8-f96f-49ed-8e1e-03da954ebc1b">
<img width="590" alt="zone3" src="https://github.com/user-attachments/assets/b4e33959-9baa-45e5-8c60-c28e437d8683">

**Comment by michaljonik** [comment]
Please enable the debug log in configuration.yaml:

```yaml
logger:
  default: info
  logs:
    satel_integra_ext.satel_integra: debug
``` 

and check the HA log when the issue happens.

**Comment by piotr0777** [comment]
Thank you! Here are the logs:

**PARTITION (STREFA) ISSUE**
Logger: homeassistant.components.alarm_control_panel
Source: components/alarm_control_panel/__init__.py:210
integration: Alarm control panel (documentation, issues)
First occurred: 22:59:53 (3 occurrences)
Last logged: 22:59:53

Entity alarm_control_panel.zone_house (<class 'custom_components.satel_integra_ext.alarm_control_panel.SatelIntegraAlarmPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.
Entity alarm_control_panel.zone_garage (<class 'custom_components.satel_integra_ext.alarm_control_panel.SatelIntegraAlarmPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.
Entity alarm_control_panel.zone_outside (<class 'custom_components.satel_integra_ext.alarm_control_panel.SatelIntegraAlarmPanel'>) is setting state directly which will stop working in HA Core 2025.11. Entities should implement the 'alarm_state' property and return its state using the AlarmControlPanelState enum, please report it to the custom integration author.

This was the only error concerning the alarm_control_panel. Seems like there are some issues but theoretically it should be fine till HA Core 2025.11

**MISSING OUTPUT ISSUE**
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:764
integration: Binary sensor (documentation, issues)
First occurred: 22:59:53 (1 occurrences)
Last logged: 22:59:53

Platform satel_integra_ext does not generate unique IDs. ID $satel_integra_ext.input$15 already exists - ignoring binary_sensor.input_15

It seems like these two parts of configuration (zone and output) collide with each other while creating unique_id

This is my config:
zones:
  15:
    name: "Input 15"
    type: "opening"
outputs:
  15:
    name: "integra_zalanie_detect"
    type: "safety"

I changed the entity.id of my input 15 (binary_sensor.input_15 to binary_sensor.input_15x), but it didn't solve the issue.

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:764
integration: Binary sensor (documentation, issues)
First occurred: 23:37:36 (1 occurrences)
Last logged: 23:37:36

Platform satel_integra_ext does not generate unique IDs. ID $satel_integra_ext.input$15 already exists - ignoring binary_sensor.input_15x

**Comment by michaljonik** [comment]
Are you sure you're using the latest version 1.0.1 of Satel Integra Extended?

**Comment by piotr0777** [comment]
Yes, I'm sure, please take a look a the screenshot:
<img width="336" alt="version" src="https://github.com/user-attachments/assets/377a335d-63b9-4ae3-98d0-23a930161526">

**Comment by michaljonik** [comment]
this one is my "dev" fork which I always sync to lashqo before a release.
I think I see the bug. Non switchable outputs use "input" in the unique_id while it should use "output" (or yet something else more unique).
I'll see if I can make a fix in the evening.

**Comment by piotr0777** [comment]
Great! Thank you! Do you have any ideas about the other issue? - Partition (Strefa) showing "Unknown" status

**Comment by michaljonik** [comment]
That one I don't know yet.
Which version of HA do you have?

**Comment by piotr0777** [comment]
Core 2024.11.0
Supervisor 2024.11.2
Operating System 13.2
Frontend 20241106.0

**Comment by michaljonik** [comment]
I see they changed something in 2024.11.
I will have to test it with this release. Before that you can try to downgrade.

**Comment by michaljonik** [comment]
Can you please test **v1.0.2-beta1** release?

**Comment by piotr0777** [comment]
Just tested **v1.0.2-beta1** release. Both issues are resolved. The Partitions (Strefy) showed up, I see the status of each Partition (Strefa) and I'm able to arm/disarm. Also the new outputs showed up after restarting.

Thanks you for quickly fixing these issues. Much appreciated!

**Comment by michaljonik** [comment]
Great to hear that, thanks for quick confirmation!
